version: '3'
services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8101:8101
    restart: always
    working_dir: /app
    command:
      [
        "poetry", "run", "uvicorn", "colors_api.api:app",
        "--host", "0.0.0.0",
        "--port", "8101"
      ]
